#!/bin/bash

python main.py -tr data/train.csv -o output -t ARDRegression
python main.py -tr data/train.csv -o output -t BayesianRidge
python main.py -tr data/train.csv -o output -t ElasticNet
python main.py -tr data/train.csv -o output -t ElasticNetCV
python main.py -tr data/train.csv -o output -t HuberRegressor
python main.py -tr data/train.csv -o output -t Lars
python main.py -tr data/train.csv -o output -t LarsCV
python main.py -tr data/train.csv -o output -t Lasso
python main.py -tr data/train.csv -o output -t LassoCV
python main.py -tr data/train.csv -o output -t LassoLars
python main.py -tr data/train.csv -o output -t LassoLarsCV
python main.py -tr data/train.csv -o output -t LassoLarsIC
python main.py -tr data/train.csv -o output -t LinearRegression
python main.py -tr data/train.csv -o output -t LogisticRegression
python main.py -tr data/train.csv -o output -t LogisticRegressionCV
python main.py -tr data/train.csv -o output -t MultiTaskLasso
python main.py -tr data/train.csv -o output -t MultiTaskLassoCV
python main.py -tr data/train.csv -o output -t MultiTaskElasticNetCV
python main.py -tr data/train.csv -o output -t OrthogonalMatchingPursuit
python main.py -tr data/train.csv -o output -t OrthogonalMatchingPursuitCV
python main.py -tr data/train.csv -o output -t PassiveAggressiveClassifier
python main.py -tr data/train.csv -o output -t PassiveAggressiveRegressor
python main.py -tr data/train.csv -o output -t Perceptron
python main.py -tr data/train.csv -o output -t RandomizedLasso
python main.py -tr data/train.csv -o output -t RandomizedLogisticRegression
python main.py -tr data/train.csv -o output -t RANSACRegressor
python main.py -tr data/train.csv -o output -t Ridge
python main.py -tr data/train.csv -o output -t RidgeClassifier
python main.py -tr data/train.csv -o output -t RidgeClassifierCV
python main.py -tr data/train.csv -o output -t RidgeCV
python main.py -tr data/train.csv -o output -t SGDClassifier
python main.py -tr data/train.csv -o output -t SGDRegressor
python main.py -tr data/train.csv -o output -t TheilSenRegressor
python main.py -tr data/train.csv -o output -t lars_path
python main.py -tr data/train.csv -o output -t lasso_path
python main.py -tr data/train.csv -o output -t lasso_stability_path
python main.py -tr data/train.csv -o output -t logistic_regression_path
python main.py -tr data/train.csv -o output -t orthogonal_mp
python main.py -tr data/train.csv -o output -t orthogonal_mp_gram
python main.py -tr data/train.csv -o output -t LinearSVC
python main.py -tr data/train.csv -o output -t SVC
